export const MSG = {
  SEND_MSG: 'SEND_MSG',
  ADD_MSG: 'ADD_MSG',
  RECEIVE_MSG: 'RECEIVE_MSG'
}

export const AUTH = {
  COOKIE: 'COOKIE',
  SIGNIN: 'SIGNIN',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAIL: 'SIGNIN_FAIL',
  SIGNOUT: 'SIGNOUT',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAIL: 'SIGNOUT_FAIL',
}

export const SOCKET = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED'
}
